kegiatan/urls.py
from os import name, pardir
from django.urls import path
from . import views

app_name = 'kegiatan'

urlpatterns = [
    path('', views.index, name='list'),
    path('new/', views.create, name='tambah'),
    path('delete/<int:id>', views.delete, name='delete'),
]

story_6/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('story_8/', include('story_8.urls')),
    path('story_9/', include('story_9.urls')),
    path('', include('kegiatan.urls'))
]

story_8/urls.py
from os import name, pardir
from django.urls import path
from . import views

app_name = 'story_8'

urlpatterns = [
    path('', views.index, name='index'),
    path('<keyword>', views.get_book, name="get_book")
]

story_9/urls.py
from os import name, pardir
from django.urls import path
from . import views

app_name = 'story_9'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.logIn, name='login'),
    path('logout/', views.logOut, name='logout'),
    path('register/', views.register, name='register')
]

kegiatan/models.py
from django.db import models
from django.db.models.fields.related import ForeignKey

# Create your models here.


class Kegiatan(models.Model):
    nama = models.CharField(max_length=50, default="")
    deskripsi = models.CharField(max_length=100, default="")


class Orang(models.Model):
    nama = models.CharField(max_length=50, default="")
    ikut = models.ForeignKey(Kegiatan, on_delete=models.CASCADE)

story_8/models.py
from django.db import models

# Create your models here.

story_9/models.py
from django.db import models

# Create your models here.

kegiatan/forms.py
from django import forms


class Input_Form(forms.Form):
    nama_kegiatan = forms.CharField(
        label='Nama Kegiatan', max_length=50, widget=forms.TextInput(attrs={'class': 'form-control'}))
    deskripsi = forms.CharField(label='Deskripsi', max_length=100, widget=forms.TextInput(
        attrs={'class': 'form-control'}))


class Orang_Form(forms.Form):
    nama_orang = forms.CharField(
        label='Nama Kegiatan', max_length=50, widget=forms.TextInput(attrs={'class': 'form-control'}))

story_9/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CreatUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email' , 'password1', 'password2']

kegiatan/views.py
# from django.forms import models
from . import models
from django.http import request
from django.http.response import HttpResponseRedirect
from django.shortcuts import redirect, render
from .models import Kegiatan, Orang
from .forms import Input_Form, Orang_Form
# Create your views here.


def index(request):
    form = Input_Form(request.POST)
    orang_form = Orang_Form(request.POST)

    if form.is_valid() and request.method == 'POST':
        data = form.cleaned_data
        new_kegiatan = Kegiatan()
        new_kegiatan.nama = data['nama_kegiatan']
        new_kegiatan.deskripsi = data['deskripsi']
        new_kegiatan.save()

    elif orang_form.is_valid() and request.method == 'POST':
        data = orang_form.cleaned_data
        print(request.POST['id_kegiatan'])
        kegiatan = Kegiatan.objects.get(id=request.POST['id_kegiatan'])
        new_orang = Orang()
        new_orang.nama = data['nama_orang']
        new_orang.ikut = kegiatan
        new_orang.save()

    list_kegiatan = Kegiatan.objects.all()
    list_kegiatan_orang = []
    for kegiatan in list_kegiatan:
        list_orang = Orang.objects.filter(ikut=kegiatan)
        data_orang = []
        for orang in list_orang:
            data_orang.append(orang)
        list_kegiatan_orang.append((kegiatan, data_orang))

    return render(request, 'list_kegiatan.html', {'kegiatans': list_kegiatan_orang, 'orang_form': Orang_Form})


def create(request):
    return render(request, 'form.html', {'form': Input_Form})


def delete(request, id):
    kegiatan_to_delete = Kegiatan.objects.get(id=id)
    Kegiatan.delete(kegiatan_to_delete)
    return redirect('kegiatan:list')

story_8/views.py
from django.shortcuts import render
import requests
from django.http.response import JsonResponse

# Create your views here.
def index(request):
    return render(request, 'story_8.html')

def get_book(request, keyword):
    url = f"https://www.googleapis.com/books/v1/volumes?q={keyword}"
    response = requests.get(url).json()
    return JsonResponse(response)

story_9/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, logout, login
from .forms import CreatUserForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.models import User


# Create your views here.
def index(request):
    return render(request, 'story_9.html')

@login_required(login_url='/admin/login/')
def logIn(request):
    return redirect("story_9:index")

def logOut(request):
    logout(request)
    return redirect("story_9:index")

def register(request):

    if request.method == 'POST':
        form = CreatUserForm(request.POST)
        if form.is_valid():
            form.save()
            user = User.objects.get(username=form.cleaned_data.get('username'))
            user.is_superuser = True
            user.is_staff = True
            user.save()

            loggedIn = authenticate(request, username=form.cleaned_data.get('username'), password=form.cleaned_data.get('password1'))
            login(request,loggedIn)

        return redirect('story_9:index')

    form = CreatUserForm()
    return render(request, 'story_9_register.html', {'form':form})

kegiatan/templates/form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Story: Muhammad Fathan Muthahhari</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
      integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-info">
      <div class="container px-4">
        <a class="navbar-brand" href="#">M Fathan M</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'kegiatan:tambah' %}">Add Kegiatan</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'kegiatan:list' %}">List Kegiatan</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">
      <h1 class="my-3">Tambah Kegiatan</h1>
      <form action="{% url 'kegiatan:list' %}" method="POST" class="form-group">
          {% csrf_token %}
          <p>Nama Kegiatan</p>
          <p>{{form.nama_kegiatan}}</p>       
          <p>Deskripsi</p>
          <p>{{form.deskripsi}}</p>
          <input type="submit" value="Tambah" class="btn btn-primary">
      </form>
    </div>

    <script
    src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"
    ></script>
    <script
    src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
    integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
    crossorigin="anonymous"
    ></script>
    <script
    src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
    integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
    crossorigin="anonymous"
    ></script>
</body> 
</html>

kegiatan/templates/list_kegiatan.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Story: Muhammad Fathan Muthahhari</title>
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
      integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-info">
      <div class="container px-4">
        <a class="navbar-brand" href="#">M Fathan M</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'kegiatan:tambah' %}">Add Kegiatan</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'kegiatan:list' %}">List Kegiatan</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="container">
      <h1 class="m-4">List Kegiatan</h1>
      <div class="d-flex flex-wrap">
        {% if kegiatans %}
            {% for kegiatan in kegiatans%}
            <div class="card m-4" style="width: 18rem;">
              <div class="card-body">
                <h5 class="card-title">{{kegiatan.0.nama}}</h5>
                <p>Deskripsi: {{kegiatan.0.deskripsi}}</p>
                {% if kegiatan.1 %}
                <p>Peserta:</p>
                <ul>
                  {% for peserta in kegiatan.1 %}
                  <li>{{peserta.nama}}</li>
                  {% endfor %}
                </ul>
                {% endif %}
                <hr>  
                <p>Ikutan dong!</p>
                <form action="{% url 'kegiatan:list'%}" method="POST" class="form-group">
                  {% csrf_token %}
                  <input type="hidden" name="id_kegiatan" value="{{kegiatan.0.id}}">
                  <p>Siapa nama kamu?</p>
                  <p>{{orang_form.nama_orang}}</p>
                  <button type="submit" class="btn btn-primary">Ikut</button>
                </form>
              <a href="{% url 'kegiatan:delete' id=kegiatan.0.id %}" class="btn btn-danger">Delete</a>
              </div>
            </div>
            {% endfor %}
        {% endif %}
      </div>
    </div>

    <script
    src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
    integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
    crossorigin="anonymous"
    ></script>
    <script
    src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
    integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
    crossorigin="anonymous"
    ></script>
    <script
    src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
    integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
    crossorigin="anonymous"
    ></script>
</body> 
</html>

story_8/templates/story_8.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <title>Story 8: Fathan Muthahhari</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="#">Fathan M</a>
    </nav>
    <div class="d-flex align-items-center flex-column">
        <form class="form-inline col-6" action="">
            <input class="form-control mr-sm-2" type="text" id="keyword" onchange="getBook()" style="width: 80%">
            <a class="btn btn-outline-success my-2" onclick="getBook()">Search</a>
        </form>
        <!-- <div class="d-flex flex-row flex-wrap justify-content-around" id="isi"> -->
        <table id="isi" class="" style="border-collapse: separate; border-spacing: 15px;">
        </table>
        <!-- </div> -->
    </div>
    
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <script>
        const getBook = async () => {
            const url = window.location.href
            const keyword = document.getElementById("keyword").value
            let stringIsi = ""
            stringIsi = stringIsi.concat(`<tr style="text-align: center">
                <th>Gambar</th>
                <th>Judul</th>
                <th>Penulis</th>
            </tr>`)
            const response = await fetch(url.concat(keyword))
            if (response.ok) {
                const jsonResponse = await response.json();
                console.log(jsonResponse)
                jsonResponse.items.map(book => (
                    stringIsi = stringIsi.concat(`
                    <tr style="text-align: center">
                        <td class"d-flex justify-content-center"> <img src="${book.volumeInfo.imageLinks.thumbnail}" class="card-img-top" alt="No Image Availabe"></td>
                        <td class"d-flex justify-content-center">${book.volumeInfo.title}</td>
                        <td class"d-flex justify-content-center">${book.volumeInfo.authors}</td>
                    </tr>
                    `)
                ))
                document.getElementById("isi").innerHTML = stringIsi
            }
        }
    </script>
</body>
</html>

story_9/templates/story_9.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>Story 9 : Muhammad Fathan M</title>
</head>
<body>
    <nav class="navbar navbar-dark bg-dark justify-content-between">
        <a class="navbar-brand text-success" href="{% url 'story_9:index' %}">Fathan M</a>
        <div>
            {% if not user.is_authenticated %}
            <a href="{% url 'story_9:register' %}"><button class="btn btn-success">Register</button></a>
            <a href="{% url 'story_9:login' %}"><button class="btn btn-success">Login</button></a>
            {% else %}
            <a href="{% url 'story_9:logout' %}"><button class="btn btn-success">Logout</button></a>
            {% endif %}
        </div>
      </nav>
      <div class="container"  style="display: flex; justify-content: center;">
          {% if user.is_authenticated %}
            <h1>Halo {{user.username}}</h1>
          {% else %}
            <h1>Login dulu yukk!!</h1>
          {% endif %}
      </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

story_9/templates/story_9_register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>Story 9 : Muhammad Fathan M</title>
</head>
<body>
    <nav class="navbar navbar-dark bg-dark justify-content-between">
        <a class="navbar-brand text-success" href="{% url 'story_9:index' %}">Fathan M</a>
        <div>
            <a href="{% url 'story_9:login' %}"><button class="btn btn-success">Login</button></a> 
        </div>
    </nav>
    <div class="container" style="display: flex; justify-content: center;">

      <div class="form-group" >
        <form method="POST" class="register-form">
          {%csrf_token%}
          <div role="alert">
            <p>Username:</p>
            {{form.username}}
            <p>Email:</p>
            {{form.email}}
            <p>Password:</p>
            {{form.password1}}
            <p>Confirm Password:</p>
            {{form.password2}}
          </div>
          <div class="form-submit">
            <input type="submit" value="Create Account" class="btn btn-success"/>
          </div>
        </form>
      </div>
    </div>


    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>